apiVersion: apps/v1
kind: Deployment
metadata:
  name: srikanth-goud-deploy
  labels:
    app: srikanth-goud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: srikanth-goud-app
  template:
    metadata:
      labels:
        app: srikanth-goud-app
    spec:
      containers:
      - name: srikanth-goud-container
        image: chsrikanthgoud/srikanth-goud-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: srikanth-goud-np-service
  labels:
    app: srikanth-goud-app
spec:
  selector:
    app: srikanth-goud-app

  type: NodePort
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
